@extends('layouts.app')

@section('title')
	Add Regular
@endsection

@section('content')
<div class="container-fluid">
	<div class="row">
		@include('layouts.nav-sidebar')
		<div class="col-md-10">
			<legend><h1>Add New Regular Member</h1></legend>
			{!! Form::open(['url' => 'regulars', 'files' => true]) !!}
			@include('layouts.forms._ra', ['submitButton' => 'Add New Member'/*, 'typeId' => 'Automatically generated by the System'*/])
		</div>
	</div>
</div>

@endsection