@extends('layouts.app')

@section('title')
	Edit Regular
@endsection

@section('content')
<div class="container-fluid">
	<div class="row">
		@include('layouts.nav-sidebar')
		<div class="col-md-10">
			<legend><h1>Edit: {{ $regular->last_name}}, {{ $regular->first_name }} {{ $regular->middle_name }}</h1></legend>
			{!! Form::model($regular, ['url' => 'regulars/' . $regular->id, 'method' => 'PATCH', 'files' => true]) !!}
			@include('layouts.forms._ra', ['submitButton' => 'Update Member'/*, 'typeId' => 'Automatically generated by the System'*/])
		</div>
	</div>
</div>

@endsection