@extends('layouts.app')

@section('title')
	Add Driver
@endsection

@section('content')
<div class="container-fluid">
	<div class="row">
		@include('layouts.nav-sidebar')
		<div class="col-md-10">
			<legend><h1>Add New Driver Member</h1></legend>
			{!! Form::open(['url' => 'drivers', 'files' => true]) !!}
			@include('layouts.forms._driver', ['submitButton' => 'Add New Driver'/*, 'typeId' => 'Automatically generated by the System'*/])
		</div>
	</div>
</div>

@endsection