@extends('layouts.app')

@section('title')
	Edit Driver
@endsection

@section('content')
<div class="container-fluid">
	<div class="row">
		@include('layouts.nav-sidebar')
		<div class="col-md-10">
			<legend><h1>Edit: {{ $driver->last_name}}, {{ $driver->first_name }} {{ $driver->middle_name }}</h1></legend>
			{!! Form::model($driver, ['url' => 'drivers/' . $driver->id, 'method' => 'PATCH', 'files' => true]) !!}
			@include('layouts.forms._driver', ['submitButton' => 'Update Driver'/*, 'typeId' => 'Automatically generated by the System'*/])
		</div>
	</div>
</div>

@endsection