@extends('layouts.app')

@section('title')
	Edit Operator
@endsection

@section('content')
<div class="container-fluid">
	<div class="row">
		@include('layouts.nav-sidebar')
		<div class="col-md-10">
			<legend><h1>Edit: {{ $operator->last_name}}, {{ $operator->first_name }} {{ $operator->middle_name }}</h1></legend>
			{!! Form::model($operator, ['url' => 'operators/' . $operator->id, 'method' => 'PATCH', 'files' => true]) !!}
			@include('layouts.forms._operator', ['submitButton' => 'Update Operator'/*, 'typeId' => 'Automatically generated by the System'*/])
		</div>
	</div>
</div>

@endsection